server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1301yashraj/initial-practice-configuration-server-repo.git
          default-label: main # branch name (e.g. master/main)
          search-paths: # optional, if configs are inside subfolders
            - configurationFolder
          username: 1301yashraj
          password: ${apikey}
